/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <errno.h>
#include <android/log.h>
#include <linux/input.h>
#include <linux/uinput.h>
/* Header for class com_example_server_Mouse */

#define MOUSE_DOWN  1
#define MOUSE_UP    0

#define DEVICE_NAME  "Virtualmouse"

#define LOGI(...) ((void)__android_log_print(ANDROID_LOG_INFO, "ServerDebug_mouse", __VA_ARGS__))
#define LOGE(...) ((void)__android_log_print(ANDROID_LOG_ERROR, "ServerDebug_mouse", __VA_ARGS__))

#ifndef _Included_com_example_server_Mouse
#define _Included_com_example_server_Mouse
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_server_Mouse_LEFTKEY_DOWN
#define com_example_server_Mouse_LEFTKEY_DOWN 1L
#undef com_example_server_Mouse_LEFTKEY_UP
#define com_example_server_Mouse_LEFTKEY_UP 0L
#undef com_example_server_Mouse_TOUCH_DOWN
#define com_example_server_Mouse_TOUCH_DOWN 3L
#undef com_example_server_Mouse_TOUCH_MOVE
#define com_example_server_Mouse_TOUCH_MOVE 5L
#undef com_example_server_Mouse_TOUCH_UP
#define com_example_server_Mouse_TOUCH_UP 4L
/*
 * Class:     com_example_server_Mouse
 * Method:    InitMouse
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_InitMouse
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_server_Mouse
 * Method:    ReleaseMouse
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_ReleaseMouse
  (JNIEnv *, jclass);

/*
 * Class:     com_example_server_Mouse
 * Method:    SendInput
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_SendInput
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_server_Mouse
 * Method:    SendTrackId
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_SendTrackId
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_server_Mouse
 * Method:    SendMtSync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_SendMtSync
  (JNIEnv *, jclass);

/*
 * Class:     com_example_server_Mouse
 * Method:    SendSync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_SendSync
  (JNIEnv *, jclass);

/*
 * Class:     com_example_server_Mouse
 * Method:    mouse_right_key
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_server_Mouse_mouse_1right_1key
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
